// ローカル保存を前提とした学習計画アプリのデータモデル
export type PlanItemType = 'study' | 'fixed' | 'lifestyle';
export type PlanItemStatus = 'planned' | 'done';
export type CreditLedgerType = 'grant' | 'spend' | 'refund';

export interface Category {
  id: string;
  name: string;
  color: string; // Tailwind class string
  createdAt: string;
}

export interface Material {
  id: string;
  name: string;
  deadline: string; // YYYY-MM-DD
  categoryId: string;
  chapters?: string[];
  createdAt: string;
}

export interface LifestyleSleep {
  startTime: number; // minutes from 0:00
  endTime: number; // minutes from 0:00
}

export interface LifestyleBlock {
  id: string;
  label: string;
  daysOfWeek: number[]; // 0=Mon ... 6=Sun
  startTime: number;
  duration: number;
  categoryId?: string;
}

export interface LifestyleTemplate {
  weekdaySleep: LifestyleSleep;
  weekendEnabled: boolean;
  weekendSleep?: LifestyleSleep;
  optionalBlocks: LifestyleBlock[];
  updatedAt: string;
}

export interface WeeklyGoal {
  id: string;
  text: string;
  completed: boolean;
}

export interface SubjectTarget {
  id: string;
  subject: string;
  material: string;
  range: string;
  content: string;
}

export interface PlanWeek {
  id: string;
  weekStartDate: string; // YYYY-MM-DD (Mon)
  weekEndDate: string; // YYYY-MM-DD
  createdAt: string;
  updatedAt: string;
  goals?: WeeklyGoal[];
  subjectTargets?: SubjectTarget[];
}

export interface PlanItem {
  id: string;
  weekId: string;
  type: PlanItemType;
  dayOfWeek: number; // 0=Mon ... 6=Sun
  startTime: number; // minutes from 0:00 (0-1800), 0-359 can be treated as next day if needed
  duration: number; // minutes (30-min step)
  categoryId?: string; // study only
  materialId?: string; // optional
  label?: string;
  notes?: string;
  status: PlanItemStatus;
  isAutoGenerated?: boolean;
  actualDuration?: number;
}

export interface CreditLedgerEntry {
  id: string;
  type: CreditLedgerType;
  amount: number;
  createdAt: string;
  memo?: string;
}

export interface AppData {
  schemaVersion: number;
  lifestyleTemplate?: LifestyleTemplate;
  categories: Category[];
  materials: Material[];
  planWeeks: PlanWeek[];
  planItems: PlanItem[];
  creditLedger: CreditLedgerEntry[];
  lastUsedCategoryId?: string;
  userName?: string;
  userGoalTitle?: string;
  userGoalDeadline?: string;
}
