import React, { useMemo, useState } from 'react';
import { addDays, addWeeks, format, parseISO } from 'date-fns';
import { CalendarDays, Plus } from 'lucide-react';

import type { AppData, Material, PlanItem } from '../types';
import { UI_TEXT } from '../constants/strings';
import { weekIdFromStart } from '../utils/plan';
import { AppChrome } from './layout/AppChrome';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from './ui/dialog';

const DAY_LABELS = ['月', '火', '水', '木', '金', '土', '日'];
const SLOT_HOURS = [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22];

type SlotTarget = {
  dayOfWeek: number;
  startTime: number;
};

function clamp(value: number, min: number, max: number) {
  return Math.min(max, Math.max(min, value));
}

function toTimeString(minutes: number) {
  const safe = ((minutes % 1440) + 1440) % 1440;
  const hour = Math.floor(safe / 60);
  const minute = safe % 60;
  return `${String(hour).padStart(2, '0')}:${String(minute).padStart(2, '0')}`;
}

function fromTimeString(value: string) {
  const [h, m] = value.split(':').map(Number);
  if (!Number.isFinite(h) || !Number.isFinite(m)) return 0;
  return clamp(h * 60 + m, 0, 1439);
}

function formatRangeLabel(start: string, end: string) {
  return `${format(parseISO(start), 'M/d')} - ${format(parseISO(end), 'M/d')}`;
}

function mapItemsByDay(items: PlanItem[]) {
  const map = new Map<number, PlanItem[]>();
  for (let day = 0; day < 7; day += 1) map.set(day, []);
  items.forEach((item) => {
    const entries = map.get(item.dayOfWeek);
    if (!entries) return;
    entries.push(item);
  });
  map.forEach((entries) => entries.sort((a, b) => a.startTime - b.startTime));
  return map;
}

export function PlanPage({
  data,
  period,
  onChangePeriod,
  onUpdateData,
  onNavigateMaterials,
  onNavigateSettings,
}: {
  data: AppData;
  period: { start: string; end: string };
  onChangePeriod: (next: { start: string; end: string }) => void;
  onUpdateData: (updater: (prev: AppData) => AppData) => void;
  onNavigateMaterials: () => void;
  onNavigateSettings: () => void;
}) {
  const weekId = useMemo(() => weekIdFromStart(period.start), [period.start]);
  const weekItems = useMemo(
    () =>
      data.planItems
        .filter((item) => item.weekId === weekId && item.type === 'study')
        .sort((a, b) => a.dayOfWeek - b.dayOfWeek || a.startTime - b.startTime),
    [data.planItems, weekId],
  );
  const itemsByDay = useMemo(() => mapItemsByDay(weekItems), [weekItems]);

  const weekDates = useMemo(() => {
    const base = parseISO(period.start);
    return Array.from({ length: 7 }, (_, index) => addDays(base, index));
  }, [period.start]);

  const [slotTarget, setSlotTarget] = useState<SlotTarget | null>(null);
  const [pickerOpen, setPickerOpen] = useState(false);

  const [editOpen, setEditOpen] = useState(false);
  const [editingItemId, setEditingItemId] = useState<string | null>(null);
  const [editDayOfWeek, setEditDayOfWeek] = useState(0);
  const [editTime, setEditTime] = useState('19:00');
  const [editDuration, setEditDuration] = useState(60);

  const openSlotPicker = (dayOfWeek: number, startTime: number) => {
    setSlotTarget({ dayOfWeek, startTime });
    setPickerOpen(true);
  };

  const addItemFromMaterial = (material: Material) => {
    if (!slotTarget) return;
    const id = `item_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
    const nextItem: PlanItem = {
      id,
      weekId,
      type: 'study',
      dayOfWeek: slotTarget.dayOfWeek,
      startTime: slotTarget.startTime,
      duration: 60,
      categoryId: material.categoryId,
      materialId: material.id,
      label: material.name,
      status: 'planned',
      isAutoGenerated: false,
    };
    onUpdateData((prev) => ({
      ...prev,
      planItems: [...prev.planItems, nextItem],
      lastUsedCategoryId: material.categoryId,
    }));
    setPickerOpen(false);
    setSlotTarget(null);
  };

  const openEdit = (item: PlanItem) => {
    setEditingItemId(item.id);
    setEditDayOfWeek(item.dayOfWeek);
    setEditTime(toTimeString(item.startTime));
    setEditDuration(item.duration);
    setEditOpen(true);
  };

  const saveEdit = () => {
    if (!editingItemId) return;
    const nextStart = fromTimeString(editTime);
    const nextDuration = clamp(Math.round(editDuration), 1, 1440);
    onUpdateData((prev) => ({
      ...prev,
      planItems: prev.planItems.map((item) =>
        item.id === editingItemId
          ? {
              ...item,
              dayOfWeek: editDayOfWeek,
              startTime: nextStart,
              duration: nextDuration,
            }
          : item,
      ),
    }));
    setEditOpen(false);
    setEditingItemId(null);
  };

  const removeItem = () => {
    if (!editingItemId) return;
    onUpdateData((prev) => ({
      ...prev,
      planItems: prev.planItems.filter((item) => item.id !== editingItemId),
    }));
    setEditOpen(false);
    setEditingItemId(null);
  };

  const nudgeItemStart = (itemId: string, diffMinutes: number) => {
    onUpdateData((prev) => ({
      ...prev,
      planItems: prev.planItems.map((item) =>
        item.id === itemId
          ? { ...item, startTime: clamp(item.startTime + diffMinutes, 0, 1439) }
          : item,
      ),
    }));
  };

  const nudgeItemDuration = (itemId: string, diffMinutes: number) => {
    onUpdateData((prev) => ({
      ...prev,
      planItems: prev.planItems.map((item) =>
        item.id === itemId
          ? { ...item, duration: clamp(item.duration + diffMinutes, 1, 1440) }
          : item,
      ),
    }));
  };

  return (
    <AppChrome title={UI_TEXT.NAV_PLAN}>
      <div className="space-y-4">
        <section className="rounded-xl border border-slate-100 bg-white p-4 shadow-sm">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div>
              <p className="text-sm text-slate-700">1週間の流れを、ゆったり確認</p>
              <p className="text-xs text-slate-500">{formatRangeLabel(period.start, period.end)}</p>
            </div>
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() =>
                  onChangePeriod({
                    start: format(addWeeks(parseISO(period.start), -1), 'yyyy-MM-dd'),
                    end: format(addWeeks(parseISO(period.end), -1), 'yyyy-MM-dd'),
                  })
                }
                className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs text-slate-600 hover:bg-slate-50"
              >
                前の週
              </button>
              <button
                type="button"
                onClick={() =>
                  onChangePeriod({
                    start: format(addWeeks(parseISO(period.start), 1), 'yyyy-MM-dd'),
                    end: format(addWeeks(parseISO(period.end), 1), 'yyyy-MM-dd'),
                  })
                }
                className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs text-slate-600 hover:bg-slate-50"
              >
                次の週
              </button>
            </div>
          </div>
          {!data.lifestyleTemplate ? (
            <div className="mt-3 rounded-lg bg-sky-50 px-3 py-2 text-xs text-sky-700">
              {UI_TEXT.MESSAGE_SETUP_LIFESTYLE}
              <button
                type="button"
                onClick={onNavigateSettings}
                className="ml-2 underline underline-offset-2"
              >
                設定を開く
              </button>
            </div>
          ) : null}
        </section>

        <section className="overflow-x-auto pb-2">
          <div className="flex min-w-max gap-3">
            {weekDates.map((date, dayOfWeek) => {
              const dayItems = itemsByDay.get(dayOfWeek) ?? [];
              return (
                <article key={dayOfWeek} className="w-[252px] shrink-0 rounded-xl border border-slate-100 bg-white p-3 shadow-sm">
                  <header className="mb-3 border-b border-slate-100 pb-2">
                    <p className="text-xs text-slate-500">
                      {format(date, 'M/d')} ({DAY_LABELS[dayOfWeek]})
                    </p>
                    <p className="text-sm text-slate-700">{UI_TEXT.LABEL_BLOCK}</p>
                  </header>

                  <div className="space-y-2">
                    {SLOT_HOURS.map((hour) => {
                      const hourStart = hour * 60;
                      const slotItems = dayItems.filter(
                        (item) => item.startTime >= hourStart && item.startTime < hourStart + 60,
                      );

                      if (slotItems.length === 0) {
                        return (
                          <button
                            key={hour}
                            type="button"
                            onClick={() => openSlotPicker(dayOfWeek, hourStart)}
                            className="flex w-full items-center justify-between rounded-lg border border-dashed border-slate-200 px-3 py-2 text-left text-xs text-slate-400 hover:bg-slate-50"
                          >
                            <span>{String(hour).padStart(2, '0')}:00</span>
                            <span>空きコマ</span>
                          </button>
                        );
                      }

                      return (
                        <div key={hour} className="space-y-2">
                          {slotItems.map((item) => {
                            const material = item.materialId
                              ? data.materials.find((entry) => entry.id === item.materialId)
                              : null;
                            return (
                              <article key={item.id} className="rounded-lg border border-sky-100 bg-sky-50 px-3 py-2">
                                <button
                                  type="button"
                                  onClick={() => openEdit(item)}
                                  className="w-full text-left"
                                >
                                  <p className="text-xs text-slate-500">
                                    {toTimeString(item.startTime)} - {toTimeString(item.startTime + item.duration)}
                                  </p>
                                  <p className="text-sm text-slate-700">
                                    {item.label ?? material?.name ?? UI_TEXT.LABEL_BLOCK}
                                  </p>
                                  <p className="text-[11px] text-slate-500">{item.duration}分</p>
                                </button>
                                <div className="mt-2 flex flex-wrap gap-1">
                                  <button
                                    type="button"
                                    onClick={() => nudgeItemStart(item.id, -1)}
                                    className="rounded border border-slate-200 bg-white px-2 py-1 text-[11px] text-slate-600 hover:bg-slate-50"
                                  >
                                    開始 -1分
                                  </button>
                                  <button
                                    type="button"
                                    onClick={() => nudgeItemStart(item.id, 1)}
                                    className="rounded border border-slate-200 bg-white px-2 py-1 text-[11px] text-slate-600 hover:bg-slate-50"
                                  >
                                    開始 +1分
                                  </button>
                                  <button
                                    type="button"
                                    onClick={() => nudgeItemDuration(item.id, -1)}
                                    className="rounded border border-slate-200 bg-white px-2 py-1 text-[11px] text-slate-600 hover:bg-slate-50"
                                  >
                                    時間 -1分
                                  </button>
                                  <button
                                    type="button"
                                    onClick={() => nudgeItemDuration(item.id, 1)}
                                    className="rounded border border-slate-200 bg-white px-2 py-1 text-[11px] text-slate-600 hover:bg-slate-50"
                                  >
                                    時間 +1分
                                  </button>
                                </div>
                              </article>
                            );
                          })}
                        </div>
                      );
                    })}
                  </div>
                </article>
              );
            })}
          </div>
        </section>

        <section className="rounded-xl border border-slate-100 bg-white p-4 shadow-sm">
          <div className="flex items-center justify-between gap-3">
            <div className="inline-flex items-center gap-2 text-sm text-slate-600">
              <CalendarDays className="h-4 w-4 text-sky-600" />
              空きコマをタップして、本棚から学習コマを入れられます
            </div>
            <button
              type="button"
              onClick={onNavigateMaterials}
              className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs text-slate-600 hover:bg-slate-50"
            >
              本棚を開く
            </button>
          </div>
        </section>
      </div>

      <Dialog
        open={pickerOpen}
        onOpenChange={(next) => {
          setPickerOpen(next);
          if (!next) setSlotTarget(null);
        }}
      >
        <DialogContent className="sm:max-w-[520px]">
          <DialogHeader>
            <DialogTitle>本棚から選ぶ</DialogTitle>
          </DialogHeader>

          {!slotTarget ? null : (
            <p className="text-xs text-slate-500">
              {DAY_LABELS[slotTarget.dayOfWeek]}曜 {toTimeString(slotTarget.startTime)} に追加します
            </p>
          )}

          {data.materials.length === 0 ? (
            <div className="space-y-3 rounded-lg border border-dashed border-slate-200 bg-slate-50 p-4 text-sm text-slate-500">
              <p>本棚にまだ本・科目がありません。</p>
              <button
                type="button"
                className="inline-flex items-center gap-1 rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs text-slate-600"
                onClick={() => {
                  setPickerOpen(false);
                  onNavigateMaterials();
                }}
              >
                <Plus className="h-4 w-4" />
                {UI_TEXT.LABEL_ADD_MATERIAL}
              </button>
            </div>
          ) : (
            <div className="grid max-h-[50vh] gap-2 overflow-y-auto pr-1">
              {data.materials.map((material) => {
                const tag = data.categories.find((category) => category.id === material.categoryId)?.name ?? '未設定';
                return (
                  <button
                    key={material.id}
                    type="button"
                    onClick={() => addItemFromMaterial(material)}
                    className="flex items-center justify-between rounded-lg border border-slate-100 bg-white px-3 py-2 text-left hover:bg-slate-50"
                  >
                    <span className="min-w-0">
                      <span className="block truncate text-sm text-slate-700">{material.name}</span>
                      <span className="block text-xs text-slate-500">{UI_TEXT.LABEL_CATEGORY}: {tag}</span>
                    </span>
                    <span className="ml-3 rounded-md bg-sky-50 px-2 py-1 text-xs text-sky-700">入れる</span>
                  </button>
                );
              })}
            </div>
          )}
        </DialogContent>
      </Dialog>

      <Dialog
        open={editOpen}
        onOpenChange={(next) => {
          setEditOpen(next);
          if (!next) setEditingItemId(null);
        }}
      >
        <DialogContent className="sm:max-w-[460px]">
          <DialogHeader>
            <DialogTitle>学習コマを調整</DialogTitle>
          </DialogHeader>

          <div className="grid gap-3 py-2">
            <label className="grid gap-1 text-sm text-slate-600">
              曜日
              <select
                value={String(editDayOfWeek)}
                onChange={(event) => setEditDayOfWeek(Number(event.target.value))}
                className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-sky-300"
              >
                {DAY_LABELS.map((label, idx) => (
                  <option key={label} value={idx}>
                    {label}
                  </option>
                ))}
              </select>
            </label>

            <label className="grid gap-1 text-sm text-slate-600">
              開始時刻（1分単位）
              <input
                type="time"
                step={60}
                value={editTime}
                onChange={(event) => setEditTime(event.target.value)}
                className="h-10 rounded-lg border border-slate-200 px-3 text-sm outline-none focus:border-sky-300"
              />
            </label>

            <label className="grid gap-1 text-sm text-slate-600">
              所要時間（分）
              <input
                type="number"
                min={1}
                max={1440}
                value={editDuration}
                onChange={(event) => setEditDuration(clamp(Number(event.target.value) || 1, 1, 1440))}
                className="h-10 rounded-lg border border-slate-200 px-3 text-sm outline-none focus:border-sky-300"
              />
            </label>
          </div>

          <DialogFooter className="gap-2">
            <button
              type="button"
              onClick={removeItem}
              className="mr-auto rounded-lg border border-orange-200 px-3 py-2 text-sm text-orange-700 hover:bg-orange-50"
            >
              削除
            </button>
            <button
              type="button"
              onClick={() => setEditOpen(false)}
              className="rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-600 hover:bg-slate-50"
            >
              キャンセル
            </button>
            <button
              type="button"
              onClick={saveEdit}
              className="rounded-lg bg-sky-600 px-3 py-2 text-sm text-white hover:bg-sky-700"
            >
              保存
            </button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </AppChrome>
  );
}
