import type { AppData, LifestyleBlock, LifestyleTemplate, PlanItem } from '../types';
import { createDefaultLifestyleTemplate } from '../data/appDataStore';

export function weekIdFromStart(start: string) {
  return `week_${start.replace(/-/g, '')}`;
}

export function getLifestyleDurationMinutes(startTime: number, endTime: number) {
  if (startTime === endTime) return 0;
  if (endTime < startTime) return endTime + 1440 - startTime;
  return endTime - startTime;
}

export function buildLifestyleItems(weekId: string, template: LifestyleTemplate): PlanItem[] {
  const items: PlanItem[] = [];
  for (let day = 0; day < 7; day += 1) {
    const isWeekend = day === 5 || day === 6;
    const sleep = template.weekendEnabled && isWeekend && template.weekendSleep ? template.weekendSleep : template.weekdaySleep;
    const sleepDuration = getLifestyleDurationMinutes(sleep.startTime, sleep.endTime);
    if (sleepDuration > 0) {
      items.push({
        id: `lifestyle_sleep_${weekId}_${day}`,
        weekId,
        type: 'lifestyle',
        dayOfWeek: day,
        startTime: sleep.startTime,
        duration: sleepDuration,
        label: '睡眠',
        status: 'planned',
        isAutoGenerated: true,
      });
    }
  }

  template.optionalBlocks.forEach((block) => {
    const days = Array.isArray(block.daysOfWeek) ? Array.from(new Set(block.daysOfWeek)) : [];
    days.forEach((day) => {
      items.push({
        id: `lifestyle_optional_${weekId}_${block.id}_${day}`,
        weekId,
        type: 'fixed',
        dayOfWeek: day,
        startTime: block.startTime,
        duration: block.duration,
        categoryId: block.categoryId,
        label: block.label,
        status: 'planned',
        isAutoGenerated: true,
      });
    });
  });

  return items;
}

export function getWeekLifestyleItemsFromData(data: AppData, weekId: string) {
  const weekItems = data.planItems.filter((item) => item.weekId === weekId);
  const overrides = weekItems.filter((item) => item.type !== 'study');
  if (overrides.length > 0) return overrides;
  const template = data.lifestyleTemplate ?? createDefaultLifestyleTemplate();
  if (template.weekdaySleep.startTime === template.weekdaySleep.endTime) return [];
  return buildLifestyleItems(weekId, template);
}

function hashKey(value: string) {
  let hash = 0;
  for (let i = 0; i < value.length; i += 1) {
    hash = (hash << 5) - hash + value.charCodeAt(i);
    hash |= 0;
  }
  return Math.abs(hash).toString(36);
}

export function buildTemplateFromWeekItems(
  weekItems: PlanItem[],
  fallback: LifestyleTemplate,
): LifestyleTemplate {
  const sleepItems = weekItems.filter((item) => item.type === 'lifestyle');
  const weekdaySleepItem =
    sleepItems.find((item) => item.dayOfWeek === 0) ??
    sleepItems.find((item) => item.dayOfWeek >= 0 && item.dayOfWeek <= 4) ??
    null;
  const weekendSleepItem =
    sleepItems.find((item) => item.dayOfWeek === 5) ??
    sleepItems.find((item) => item.dayOfWeek === 6) ??
    null;

  const weekdaySleep = weekdaySleepItem
    ? {
        startTime: weekdaySleepItem.startTime,
        endTime: (weekdaySleepItem.startTime + weekdaySleepItem.duration) % 1440,
      }
    : fallback.weekdaySleep;

  const weekendSleep = weekendSleepItem
    ? {
        startTime: weekendSleepItem.startTime,
        endTime: (weekendSleepItem.startTime + weekendSleepItem.duration) % 1440,
      }
    : fallback.weekendSleep;

  const weekendEnabled =
    Boolean(weekendSleepItem) &&
    (weekdaySleep.startTime !== weekendSleep?.startTime || weekdaySleep.endTime !== weekendSleep?.endTime);

  const fixedItems = weekItems.filter((item) => item.type === 'fixed');
  const blocks = new Map<string, LifestyleBlock>();

  fixedItems.forEach((item) => {
    const label = item.label ?? '固定予定';
    const key = `${label}|${item.startTime}|${item.duration}|${item.categoryId ?? ''}`;
    const id = `block_${hashKey(key)}`;
    const existing = blocks.get(key);
    if (existing) {
      if (!existing.daysOfWeek.includes(item.dayOfWeek)) {
        existing.daysOfWeek.push(item.dayOfWeek);
      }
      return;
    }
    blocks.set(key, {
      id,
      label,
      daysOfWeek: [item.dayOfWeek],
      startTime: item.startTime,
      duration: item.duration,
      categoryId: item.categoryId,
    });
  });

  return {
    ...fallback,
    weekdaySleep,
    weekendEnabled,
    weekendSleep: weekendEnabled ? weekendSleep ?? fallback.weekendSleep : undefined,
    optionalBlocks: Array.from(blocks.values()).sort((a, b) => a.startTime - b.startTime),
    updatedAt: new Date().toISOString(),
  };
}

export function computeAvailableMinutes(template: LifestyleTemplate | undefined) {
  if (!template) return 0;
  const totalWeekMinutes = 7 * 24 * 60;
  let lifestyleMinutes = 0;
  for (let day = 0; day < 7; day += 1) {
    const isWeekend = day === 5 || day === 6;
    const sleep = template.weekendEnabled && isWeekend && template.weekendSleep ? template.weekendSleep : template.weekdaySleep;
    lifestyleMinutes += getLifestyleDurationMinutes(sleep.startTime, sleep.endTime);
  }
  lifestyleMinutes += template.optionalBlocks.reduce((sum, block) => {
    const count = Array.isArray(block.daysOfWeek) ? block.daysOfWeek.length : 0;
    return sum + block.duration * count;
  }, 0);
  return Math.max(0, totalWeekMinutes - lifestyleMinutes);
}

export function computeAvailableMinutesFromItems(items: PlanItem[]) {
  const totalWeekMinutes = 7 * 24 * 60;
  const lifestyleMinutes = items.reduce((sum, item) => sum + item.duration, 0);
  return Math.max(0, totalWeekMinutes - lifestyleMinutes);
}

export function computeCategoryTotals(items: PlanItem[]) {
  const totals = new Map<string, number>();
  items.forEach((item) => {
    if (!item.categoryId) return;
    const minutes = item.actualDuration ?? item.duration;
    totals.set(item.categoryId, (totals.get(item.categoryId) ?? 0) + minutes);
  });
  return totals;
}
